### ISSUE TITLE
Ingredient Amounts

### ISSUE THREAD

**Issue by CyBharda** [RaymondWise/Excel-Weekly-Meal-Plan-Shopping-List-Generator#10]
GDay,

Firstly, your spreadsheet is brilliant, exactly what I was looking for, thank you! Just wondering if you could extend out the shopping list to compile the amount of the ingredient required.

For example, two nights in a row I want to cook Beef Stroganoff. So I select and build the shopping list, but it only lists the ingredients, not how much I will need. Of course I'll need double the amount of ingredients, as I am cooking it twice.

I also thought, what if you put in the amount of ingredients needed for 1 person or serving. That way you could specify how many people you are cooking for and the shopping list automatically calculated the amount of ingredients you require to have enough food for the number of people being catered for.

I might try to give that a go myself or am happy to work with you to get that done.

Cheers,
Cy

**Comment by RaymondWise** [comment]
Sure, it should be pretty simple with the first request, you'd just need to store an array of ingredients with # of occurrences prior to calling [OSXRemoveIngredients](https://github.com/RaymondWise/Excel-Weekly-Meal-Plan-Shopping-List-Generator/blob/8afe004632fa11b431cf708c90dedf5dfef61513/Populate.bas#L112) (line #112).

The logic for how much ingredient per serving, that would be a little more complex. It's possible to expand it so that you put the ingredients for each choice with the amount of it and then select the number of people for each meal and have it print out like that. It could also probably print out the meal name with the ingredients and amounts if needed.

Feel free to branch and give it a shot. I'll see if I can get to work on it sometime soon, but honestly right now I'm living at a hotel overseas so I don't have my main machine.

**Comment by RaymondWise** [comment]
Been thinking on it and there would need to be a way for a user to pick imperial or metric measurements. You know, 500g of chicken or 20 oz of chicken.

**Comment by RaymondWise** [comment]
'Many food items have the same ingredients
     wsShopping.Range("A:A").RemoveDuplicates Columns:=1, Header:=xlNo

This will have to be made much more robust with an entirely different method

**Comment by RaymondWise** [comment]
1.  Must rework structure of meals in meal storage sheets https://github.com/RaymondWise/Excel-Weekly-Meal-Plan-Shopping-List-Generator/issues/13
2. Must rework shopping list structure to include ingredients https://github.com/RaymondWise/Excel-Weekly-Meal-Plan-Shopping-List-Generator/issues/14
3. Must alter removal of duplicates to ensure ingredient amounts are totalled https://github.com/RaymondWise/Excel-Weekly-Meal-Plan-Shopping-List-Generator/issues/12

**Comment by RaymondWise** [comment]
Closing as this has been split up into smaller issues
