### ISSUE TITLE
Marking ingredients on hand

### ISSUE THREAD

**Issue by RaymondWise** [RaymondWise/Excel-Weekly-Meal-Plan-Shopping-List-Generator#16]
Sometimes you might already have ingredients on hand, e.g. spices or dressing

Right now, you must cross those off the list after printing. Maybe there is a way to remove this prior to printing? I'm not sure.

**Comment by JRated** [comment]
I think considering how much the sheet already offers this wouldn't be necessary. Otherwise I guess it's create another tab, that lists all the ingredients from our generated shopping list, and minus's amounts we type in somewhere for what we already have - but seems like a lot of coding/user input for little payback

**Comment by RaymondWise** [comment]
@JRated true, I was thinking more of just being able to get the ingredient list and click what you don't need to get so it doesn't print. Then again, maybe that isn't needed at all.

**Comment by RaymondWise** [comment]
Other priorities take precedent. I'm scapping this feature for now
